package com.codeheadsystems.minidirectory.server.dto;

import com.codeheadsystems.minidirectory.model.Account;
import com.codeheadsystems.minidirectory.model.GrantSpec;
import com.codeheadsystems.minidirectory.model.PrincipalKind;
import com.codeheadsystems.minidirectory.model.ResolvedPrincipal;
import com.codeheadsystems.minipolicy.Grant;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import java.util.ArrayList;
import java.util.List;

/**
 * Request and response bodies for the admin and resolution APIs.
 *
 * <p>The same authorization vocabulary — {@code admin} + {@code memberOf} + {@code roles} +
 * {@code grants} (each a flat {@link GrantSpec}) — is used on create, on assignment, and in the
 * stored {@link Account}, so the API speaks one shape end to end. Crucially, {@link AccountView}
 * (and every list/read response) omits the secret hash entirely: the directory never returns secret
 * material except the one-time service-account secret at creation ({@link ServiceAccountCreated}).
 */
public final class Dtos {

  private Dtos() {
  }

  /**
   * Body of {@code POST /admin/humans}.
   *
   * @param id          the operator-chosen id (e.g. a username); required.
   * @param displayName optional human label.
   * @param admin       whether the human holds the control/admin capability.
   * @param memberOf    group ids the human joins (may be null = none).
   * @param roles       role ids assigned directly (may be null = none).
   * @param grants      direct grants (may be null = none).
   */
  @JsonIgnoreProperties(ignoreUnknown = true)
  public record CreateHumanRequest(String id, String displayName, boolean admin,
                                   List<String> memberOf, List<String> roles, List<GrantSpec> grants) {
  }

  /**
   * Body of {@code POST /admin/service-accounts}. The id and secret are generated by the server.
   *
   * @param displayName optional human label.
   * @param admin       whether the service account holds the control/admin capability.
   * @param memberOf    group ids it joins (may be null = none).
   * @param roles       role ids assigned directly (may be null = none).
   * @param grants      direct grants (may be null = none).
   */
  @JsonIgnoreProperties(ignoreUnknown = true)
  public record CreateServiceAccountRequest(String displayName, boolean admin, List<String> memberOf,
                                            List<String> roles, List<GrantSpec> grants) {
  }

  /**
   * Response of {@code POST /admin/service-accounts}: includes the one-time plaintext secret. This
   * is the only time the secret is returned; it is not recoverable later.
   *
   * @param id          the generated service-account id.
   * @param secret      the one-time plaintext secret (store it now).
   * @param displayName the human label, if any.
   * @param account     the created account as a (secret-free) view.
   */
  public record ServiceAccountCreated(String id, String secret, String displayName, AccountView account) {
  }

  /**
   * Body of {@code PUT /admin/principals/{id}/assignment}: replaces an account's authorization.
   *
   * @param enabled  whether the account remains active.
   * @param admin    whether it holds the control/admin capability.
   * @param memberOf group ids it belongs to (may be null = none).
   * @param roles    role ids assigned directly (may be null = none).
   * @param grants   direct grants (may be null = none).
   */
  @JsonIgnoreProperties(ignoreUnknown = true)
  public record AssignmentRequest(boolean enabled, boolean admin, List<String> memberOf,
                                  List<String> roles, List<GrantSpec> grants) {
  }

  /**
   * Body of {@code POST /admin/service-accounts/authenticate}: a token issuer presents a client's
   * credentials for verification (the secret is verified server-side, never stored or echoed).
   */
  @JsonIgnoreProperties(ignoreUnknown = true)
  public record VerifyServiceAccountRequest(String id, String secret) {
  }

  /** Body of {@code POST /admin/roles}. */
  @JsonIgnoreProperties(ignoreUnknown = true)
  public record RoleRequest(String id, String description, List<GrantSpec> grants) {
  }

  /** Body of {@code PUT /admin/roles/{id}}. */
  @JsonIgnoreProperties(ignoreUnknown = true)
  public record RoleUpdateRequest(String description, List<GrantSpec> grants) {
  }

  /** Body of {@code POST /admin/groups}. */
  @JsonIgnoreProperties(ignoreUnknown = true)
  public record GroupRequest(String id, String description, List<String> roles, List<GrantSpec> grants) {
  }

  /** Body of {@code PUT /admin/groups/{id}}. */
  @JsonIgnoreProperties(ignoreUnknown = true)
  public record GroupUpdateRequest(String description, List<String> roles, List<GrantSpec> grants) {
  }

  /**
   * An account as returned by the admin API — deliberately WITHOUT any secret hash.
   *
   * @param id          the account id (a mini-policy principal id / token {@code sub}).
   * @param kind        whether this is a human or a service account.
   * @param displayName the human label, if any.
   * @param admin       whether it holds the control/admin capability.
   * @param enabled     whether it is currently active.
   * @param memberOf    group memberships.
   * @param roles       directly-assigned roles.
   * @param grants      directly-assigned grants.
   */
  @JsonInclude(JsonInclude.Include.NON_NULL)
  public record AccountView(String id, PrincipalKind kind, String displayName, boolean admin,
                            boolean enabled, List<String> memberOf, List<String> roles,
                            List<GrantSpec> grants) {

    /** Project a stored account into its safe view (drops the secret hash). */
    public static AccountView from(final Account account) {
      return new AccountView(account.id(), account.kind(), account.displayName(), account.admin(),
          account.enabled(), account.memberOf(), account.roles(), account.grants());
    }
  }

  /**
   * Response of {@code GET /admin/principals/{id}/resolution}: the account resolved to a mini-policy
   * principal and its fully-expanded, de-duplicated grants — exactly the inputs a policy engine
   * decides over.
   *
   * @param id     the principal id.
   * @param admin  whether the principal holds the control/admin capability.
   * @param grants the effective, flattened grants (roles and group memberships already expanded).
   */
  public record ResolutionView(String id, boolean admin, List<GrantSpec> grants) {

    /** Project a {@link ResolvedPrincipal} (which carries mini-policy {@link Grant}s) into wire form. */
    public static ResolutionView from(final ResolvedPrincipal resolved) {
      final List<GrantSpec> grants = new ArrayList<>();
      for (final Grant grant : resolved.grants()) {
        grants.add(GrantSpec.from(grant));
      }
      return new ResolutionView(resolved.principal().id(), resolved.principal().admin(), grants);
    }
  }
}
